# -*- coding: utf-8 -*-
"""lab1task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VMfWn-LOxSA3_OX1bYVAif22z5xr0zer

here i have imported the random library to choose randomly students.
"""

import random
import os
import time

"""mounted google drive"""

from google.colab import drive
drive.mount('/content/drive')

f =open("/content/drive/MyDrive/lab1task/lab1.txt",  "r")
print(f.read())

"""at first this function will take the student from text file and select for viva.strip()func will erase the extra space,comma."""

#here at first read the ids

def read_student_ids(file_name):
    if not os.path.exists(file_name):
        raise FileNotFoundError(f"The file '{file_name}' was not found.")

    with open(file_name, 'r') as file:

        student_ids = [line.strip() for line in file.readlines()]


    if not student_ids:
        raise ValueError(f"The file '{file_name}' is empty.")

    return student_ids
# Step 2: Maintain a list of students who haven’t been selected yet
def select_students_for_viva(student_ids):
    remaining_students = student_ids.copy()
    selected_students = []

    viva_number = 1


    while remaining_students:
        selected_student = random.choice(remaining_students)
        remaining_students.remove(selected_student)
        selected_students.append(selected_student)
        print(f"Viva #{viva_number}: Selected student: {selected_student}")

        viva_number += 1


    print("\nAll students have been selected for the viva. Resetting list...")
    return selected_students, student_ids

def track_viva_time(student_ids):
    start_time = time.time()  # Track start time
    selected_students, reset_list = select_students_for_viva(student_ids)
    end_time = time.time()  # Track end time

    elapsed_time = end_time - start_time
    print(f"\nTime taken for this round: {elapsed_time:.2f} seconds.")

    return selected_students, reset_list
#if file doesnt consist any id's or file is not found it will use the try except block in python
def main():
    file_name = "/content/drive/MyDrive/lab1task/lab1.txt"

    try:
        student_ids = read_student_ids(file_name)
    except (FileNotFoundError, ValueError) as e:
        print(f"Error: {e}")
        return

   # Perform the selection process also viva time
    selected_students, reset_list = select_students_for_viva(student_ids)
    selected_students, reset_list = track_viva_time(student_ids)


    print("\nResetting the list of students.")
    remaining_students = reset_list.copy()


    print(f"Reset list of students: {remaining_students}")

if __name__ == "__main__":
    main()